top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/arch/unix
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/arch/unix
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/arch/unix

include $(top_srcdir)/build/special.mk

