top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/dav/main
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/dav/main
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
