#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE "cyrus-sasl"
#define VERSION "2.1.25"
#define HAVE___ATTRIBUTE__ 1
#define SASL_DB_PATH "/etc/sasldb2"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define SASL_DEV_RANDOM "/dev/random"
#define HAVE_SYSLOG 1
#define HAVE_AUTHDAEMON /**/
#define PATH_AUTHDAEMON_SOCKET "/dev/null"
#define DO_SASL_CHECKAPOP /**/
#define SIZEOF_LONG 8
#define HAVE_OPENSSL /**/
#define WITH_SSL_DES /**/
#define WITH_DES /**/
#define DO_DLOPEN /**/
#define PLUGINDIR "/usr/lib/sasl2"
#define CONFIGDIR "/usr/lib/sasl2:/etc/sasl2"
#define WITH_RC4 /**/
#define HAVE_GETSUBOPT /**/
#define HAVE_SNPRINTF /**/
#define HAVE_VSNPRINTF /**/
#define HAVE_LIBRESOLV 1
#define HAVE_GETADDRINFO /**/
#define HAVE_GETNAMEINFO /**/
#define RETSIGTYPE void
#define TIME_WITH_SYS_TIME 1
#define STDC_HEADERS 1
#define HAVE_DIRENT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_DLFCN_H 1
#define HAVE_FCNTL_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_PATHS_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_UNISTD_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYSEXITS_H 1
#define HAVE_STDARG_H 1
#define HAVE_SS_FAMILY /**/
#define HAVE_SOCKLEN_T /**/
#define HAVE_GETHOSTNAME 1
#define HAVE_GETDOMAINNAME 1
#define HAVE_GETPWNAM 1
#define HAVE_GETSPNAM 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_INET_ATON 1
#define HAVE_MEMCPY 1
#define HAVE_MKDIR 1
#define HAVE_SELECT 1
#define HAVE_SOCKET 1
#define HAVE_STRCHR 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRSPN 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_JRAND48 1
#define HAVE_STRUCT_SOCKADDR_STORAGE /**/
