top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/event
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/event
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/event
include $(top_srcdir)/build/special.mk
