top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/echo
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/echo
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/echo

include $(top_srcdir)/build/special.mk

