top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/worker
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/worker
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/server/mpm/worker

include $(top_srcdir)/build/special.mk
