#define DCS_CHANNEL_CHANGED_MSG "°ÊºAÀW¹D·j´M¤w±N³q¹D¥Ñ%d§ï¬°%d"
#define LIB_DDNS_BAD_AUTH                 "µn¤J¥¢±Ñ(¨Ï¥ÎªÌ¦WºÙ©Î±K½X)"
#define LIB_DDNS_BLOCKED                  "³s½u¤w³Qªý¾×"
#define LIB_DDNS_CONN_FAIL                "³s½u¥¢±Ñ"
#define LIB_DDNS_CUSTOM_DNS_NOT_ACT       "¤â°Ê³]©wDNS¦øªA¾¹¥¼±Ò¥Î"
#define LIB_DDNS_DDNS_ERROR               "DNS¿ù»~"
#define LIB_DDNS_DOMAIN_NOT_SUPPORTED     "½Ð´£¨Ñ¤w»{ÃÒºô°ì"
#define LIB_DDNS_HOSTNAME_IS_BLOCKED_BY_ABUSE     "ºô°ì¦WºÙ¦]ÀÝ¥Î³Qªý¾×"
#define LIB_DDNS_HOSTNAME_NOT_EXIST       "ºô°ì¦WºÙ¤£¦s¦b"
#define LIB_DDNS_NOT_YOURS                "ºô°ì¦WºÙ«D¨Ï¥ÎªÌ¾Ö¦³"
#define LIB_DDNS_ONLY_ONE_DOMAIN          "ºô°ì¦WºÙ¤w³Qµù¥U"
#define LIB_DDNS_PARAMETER_INVALID        "°Ñ¼ÆµL®Ä"
#define LIB_DDNS_SERVER_SHUTDOWN          "¦øªA¾¹Ãö³¬"
#define LIB_DDNS_SUCCESS                  "§ó·s¦¨¥\""
#define LIB_DDNS_TOO_MANY_OR_FEW          "§ä¨ì¤Ó¦h©Î¤Ó¤Ö¥D¾÷"
#define LIB_DDNS_UNKNOWN_ERROR            "¥¼ª¾¿ù»~"
#define LIB_DDNS_USER_IS_NOT_A_DONATOR    "¨Ï¥ÎªÌ¨Ã«D¥I¶O¨Ï¥ÎªÌ"
#define LOGIN_LOG_WRITE_FAIL "IP : %s µn¤J¥¢±Ñ"
#define LOGIN_LOG_WRITE_TRUE "IP : %s ³s½u¦¨¥\""
#define SMTP_MESSAGE_STRING "SMTP°T®§"
#define SYSLOG_CHANGE_DHCP_GATEWAY_ADDR "DHCP¹h¹D¦ì§}¦bDHCP§ó·s®É¤wÅÜ§ó[ %s -> %s ]"
#define SYSLOG_CHANGE_DHCP_IP_CONFIG "IP¦ì§}¦bDHCP§ó·s®É¤wÅÜ§ó"
#define SYSLOG_CONFIG_RESTORE_FAILED		 "³]¸mÁÙ­ì¥¢±Ñ - ÀÉ®×¦WºÙ"
#define SYSLOG_CONFIG_RESTORE_FAILED_NOFILE	 "³]¸mÁÙ­ì¥¢±Ñ - µLÀÉ®×¦WºÙ"
#define SYSLOG_CONFIG_RESTORE_SUCCESS		 "³]¸mÁÙ­ì¦¨¥ - ÀÉ®×¦WºÙ"
#define SYSLOG_CUPSD_TITLE "Network Printer Server"
#define SYSLOG_DDNS_SERVER_CONNECTED "¤w¦¨¥\³s½u¦ÜDDNS¦øªA¾¹"
#define SYSLOG_DHCP_RESTART_BY_WAN_LINK_OFF "WAN%d¤w³s½u¡ADHCP¥Î¤áºÝ­«·s±Ò¥Î¡C"
#define SYSLOG_DYN_IP                            "DHCP"
#define SYSLOG_EMAIL_SEND_TIMEOUT       "SMTP³s½u: ¹O®É§iÄµ²×¤î"
#define SYSLOG_EMAIL_SUBJECT "¨t²Î¬ö¿ýÀÉ³ø§i"
#define SYSLOG_INVALID_ADMIN_EMAIL_CONFIG       "ºÞ²z­ûE-mail³]©w¿ù»~"
#define SYSLOG_IP_CONFLICT "IP½Ä¬ð"
#define SYSLOG_LOG_CONTENT  "¨t²Î¬ö¿ýÀÉ¤º®e"
#define SYSLOG_LOG_HISTORY "¨t²Î¬ö¿ýÀÉ¾ú¥v¬ö¿ý"
#define SYSLOG_LOG_TIME  "®É¶¡"
#define SYSLOG_MSG_ADMIN_CHANGE_INTERNAL_IP	"ºÞ²z­ûÅÜ§ó°Ï°ìºô¸ô(¤º³¡)IP"
#define SYSLOG_MSG_ADMIN_CHANGE_PASS		"ºÞ²z­ûÅÜ§ó¨Ï¥ÎªÌ¦WºÙ¤Î±K½X"
#define SYSLOG_MSG_ADMIN_CHANGE_PORTLINK	"ºÞ²z­ûÅÜ§ó³s½u(³q°T°ð)³]©w"
#define SYSLOG_MSG_ADMIN_CHANGE_WANCONF		"ºÞ²z­ûÅÜ§óºô¸ô³s½u³]©w"
#define SYSLOG_MSG_ADMIN_INTERNET_CONN "ºÞ²z­û­«³sºô»Úºô¸ô"
#define SYSLOG_MSG_ADMIN_INTERNET_DISCONN "ºÞ²z­û¤¤Â_ºô»Úºô¸ô"
#define SYSLOG_MSG_ADMIN_RESTART		"ºÞ²z­ûµo°e­«±Ò«ü¥O"
#define SYSLOG_MSG_ADMIN_RUN_DHCPD		"ºÞ²z­û±Ò¥ÎDHCP¦øªA¾¹"
#define SYSLOG_MSG_ADMIN_STOP_DHCPD		"ºÞ²z­û°±¥ÎDHCP¦øªA¾¹"
#define SYSLOG_MSG_AUTOREBOOT "[¦Û°Ê©w´Á­«±Ò]¥\¯à­«·s±Ò°Ê¸ô¥Ñ¾¹"
#define SYSLOG_MSG_CHANGED_PRIMARY_WAN "¥D­nWAN³s±µ°ð¤wÅÜ§ó"
#define SYSLOG_MSG_CHANGE_WAN_REBOOT "ºÞ²z­ûÅÜ§óWAM³s±µ°ð³]©w"
#define SYSLOG_MSG_CSRF_BLOCK "°»´ú´c·N½s½X(CSRF): "
#define SYSLOG_MSG_DDNS_FAILED			"DDNSµù¥U¥¢±Ñ"
#define SYSLOG_MSG_DDNS_SUCCESS			"DDNSµù¥U¦¨¥\""
#define SYSLOG_MSG_DHCPC_LEASE "WAN IP¯²¬ù¹O®É:ºô»Úºô¸ô¤¤Â_³s½u"
#define SYSLOG_MSG_DHCPC_RCV_IP			"DHCP¥Î¤áºÝ¤w³s½uWAN"
#define SYSLOG_MSG_DHCPC_SERVER_TIMEOUT		"WANºÝDHCP¦øªA¾¹µL¦^À³"
#define SYSLOG_MSG_DHCPD_OFFER_IP		"DHCP¦øªA¾¹µo©ñIP"
#define SYSLOG_MSG_DHCP_SERVER_RESUME "DHCP¦øªA¾¹¤w«ì´_"
#define SYSLOG_MSG_DHCP_SERVER_SUSPENDED "DHCP¦øªA¾¹¼È°±ªA°È,¦]°Ï°ìºô¸ô¤º°»´ú¨ì¨ä¥LDHCP¦øªA¾¹"
#define SYSLOG_MSG_DNS_APPLY "ºÞ²z­û (%s) ³]¸mDNS¬°%s,%s¡C"
#define SYSLOG_MSG_EMAIL_AUTH_FAILED		"SMTPÅçÃÒ¥¢±Ñ"
#define SYSLOG_MSG_EMAIL_ND_SUCCESS          "ºô¸ôÀË´ú¤é»xE-mailµo°e¦¨¥\""
#define SYSLOG_MSG_EMAIL_REPORT_UNKNOWN_SMTP_SERVER "E-mail³ø§iµo°e¥¢±Ñ:§ä¤£¨ìSMTP¦øªA¾¹"
#define SYSLOG_MSG_EMAIL_SYSLOG_SUCCESS          "¨t²Î¬ö¿ýÀÉE-mailµo°e¦¨¥\""
#define SYSLOG_MSG_FAKEDNS_START 	"ºÞ²z­û±Ò¥Î'¦Û°Ê³s½u³]©w-­¶­±'"
#define SYSLOG_MSG_FAKEDNS_STOP 	"ºÞ²z­û°±¥Î'¦Û°Ê³s½u³]©w-­¶­±'"
#define SYSLOG_MSG_FIRMWARE_UPGRADE		"ºÞ²z­û¤É¯Å¨t²Î"
#define SYSLOG_MSG_INVALID_PPP_ACCOUNT		"PPPoE³s½u±b¸¹©Î±K½X¿ù»~"
#define SYSLOG_MSG_IPCONFLICT  "IP½Ä¬ð"
#define SYSLOG_MSG_KAID_AUTH_ERROR "PSP-KAIÅçÃÒ¿ù»~(1)"
#define SYSLOG_MSG_KAID_DOWNLOAD_ERROR "PSP-KAI¤U¸ü¿ù»~(1)"
#define SYSLOG_MSG_KAID_RESTARTED "KAI Engine¤w­«·s±Ò°Ê"
#define SYSLOG_MSG_MAIL_CONNECT_ERROR           "±H°e¶l¥ó®ÉµLªk³s±µ¶l¥ó¦øªA¾¹"
#define SYSLOG_MSG_MAIL_UNKNOWN_MAIL_SERVER     "±H°e¶l¥ó®É§ä¤£¨ì¶l¥ó¦øªA¾¹"
#define SYSLOG_MSG_MAKE_SCHED_1 "ºô»Úºô¸ôªA°È¥Ø«eµLªk¨Ï¥Î¦]¤w³Q±Æµ{ªý¾×"
#define SYSLOG_MSG_MAKE_SCHED_2 "¦p­n¨Ï¥Îºô¸ôºô¸ô¡A½ÐÁpµ¸ºô¸ôºÞ²z­û"
#define SYSLOG_MSG_MASTER_AP_CHANNEL_CHANGED "[WDS]¥DAP³q¹D¤wÅÜ§ó"
#define SYSLOG_MSG_MASTER_AP_FOUND "¦¨¥\§ä¨ì¥DAP"
#define SYSLOG_MSG_MASTER_AP_NOT_FOUND "µLªk§ä¨ì¥DAP"
#define SYSLOG_MSG_NAT_OFF	"ºÞ²z­û°±¥ÎNAT"
#define SYSLOG_MSG_NAT_ON	"ºÞ²z­û±Ò¥ÎNAT"
#define SYSLOG_MSG_NO_MASTER_BEACON "»P¥DAP¤¤Â_³s½u"
#define SYSLOG_MSG_PPP_CONNECTED		"WANºÝ¤w³s±µPPPoEºô¸ô"
#define SYSLOG_MSG_PPP_DISCONNECTED		"PPPoE³s½u¤¤Â_"
#define SYSLOG_MSG_PPP_NO_REPONSE		"WANºÝPPPoE¦øªA¾¹µL¦^À³"
#define SYSLOG_MSG_PRINTER_RECOGNIZED "¤w¿ëÃÑUSB¦Lªí¾÷"
#define SYSLOG_MSG_RESTART			"¨t²Î¤w­«·s±Ò°Ê( Version: %s)"
#define SYSLOG_MSG_SAVECONF 	"©Ò¦³³]©w¤wÀx¦s"
#define SYSLOG_MSG_UPNP_START 	"ºÞ²z­û±Ò¥ÎUPNP(¨t²Î­«±Ò)"
#define SYSLOG_MSG_UPNP_STOP 	"ºÞ²z­û°±¥ÎUPNP"
#define SYSLOG_MSG_WAN1_FAIL	"WAN1ºÝ³s½u¤¤Â_¡A¤wÂà²¾¦ÜWAN2³s½u"
#define SYSLOG_MSG_WAN1_OK	"WAN1¤w³s½u"
#define SYSLOG_MSG_WAN2_FAIL	"WAN2ºÝ³s½u¤¤Â_¡A¤wÂà²¾¦ÜWAN1³s½u"
#define SYSLOG_MSG_WAN2_OK	"WAN2¤w³s½u"
#define SYSLOG_MSG_WPS_FAIL	"·s¼WWPS³]³Æ¥¢±Ñ"
#define SYSLOG_MSG_WPS_OK	"·s¼WWPS³]³Æ¦¨¥\""
#define SYSLOG_NASCONF_AFP_RUN   "Service"
#define SYSLOG_NASCONF_AFP_TITLE "AFP"
#define SYSLOG_NASCONF_APACHE_TITLE    "Apache¦øªA¾¹"
#define SYSLOG_NASCONF_CLOUDBACKUP_TITLE "¶³ºÝ³Æ¥÷"
#define SYSLOG_NASCONF_FTP_TITLE     "FTP ªA°È"
#define SYSLOG_NASCONF_ITUNES_TITLE "iTunes¦øªA¾¹"
#define SYSLOG_NASCONF_MEDIA_TITLE "´CÅé¦øªA¾¹"
#define SYSLOG_NASCONF_MYSQL_TITLE     "MySQL¦øªA¾¹"
#define SYSLOG_NASCONF_SAMBA_TITLE   "WindowsÀÉ®×¦@¨É(SAMBA)"
#define SYSLOG_NASCONF_TORRENT_TITLE "Torrent"
#define SYSLOG_NASCONF_URL_TITLE     "ºô§} ªA°È"
#define SYSLOG_NAS_SERVICE_FOLDER_NOT_FOUND_STOPPED "§ä¤£¨ì¤w³]©w¸ê®Æ§¨¡C %s ªA°È¤w²×¤î"
#define SYSLOG_NAS_SERVICE_STARTED      "%s¤w±Ò°Ê "
#define SYSLOG_NAS_SERVICE_STOPPED "%s¤wÃö³¬"
#define SYSLOG_NAS_SERVICE_UNINSTALLED_STOPPED "%s ©|¥¼¦w¸Ë"
#define SYSLOG_NAS_SERVICE_UPGRADE_PLUGIN "%s - ¤w°»´ú¨ì·sª©¨Ã¤É¯Å"
#define SYSLOG_PPPOE                             "PPPoE"
#define SYSLOG_PPPOE_SCHED_RESUME_MESSAGE "PPPoE³s½u¤w¨Ì¾ÚPPPoE³s½u®É¶¡³]©w«ì´_: %s"
#define SYSLOG_PPPOE_SCHED_STOP_MESSAGE "PPPoE³s½u¤w¨Ì¾ÚPPPoE³s½u®É¶¡³]©w°±¤î: %s"
#define SYSLOG_PPTP                	         "VPN IP"
#define SYSLOG_PPTP_CONNECTED			 "PPTP VPN ¤w³s½u - ±b¸¹ : %s / %s"
#define SYSLOG_PPTP_DISCONNECTED		 "PPTP VPN ¤¤Â_ - ±b¸¹ :"
#define SYSLOG_PRIVATE_IP_ASSIGN "¹jÂ÷¨Ó¦ÛWANºÝªºµêÀÀIP(%s)µo©ñ"
#define SYSLOG_RECEIVE_INTERNAL_IP "ºô»Úºô¸ô³s½u¿ù»~:WAN IP½d³ò»P¤º³¡ºô¸ô¬Û¦P"
#define SYSLOG_RECEIVE_PRIVATE_IP "µêÀÀIPºô»Úºô¸ô³s½u¤w¸T¤î"
#define SYSLOG_SAME_SUBNET_IP_ASSIGN "WAN IP»P¤º³¡°Ï°ìºô¸ôIP¬Û¦P"
#define SYSLOG_SAVE_FAILED "¤wµL³]©wªÅ¶¡¡CµLªkÀx¦s§ó¦h³]©w¸ê®Æ"
#define SYSLOG_SMART_QOS_DEL    "Smart QoS : %s ¤w§R°£"
#define SYSLOG_SMART_QOS_NEW    "Smart QoS : %s ¤w·s¼W"
#define SYSLOG_STATIC_IP                         "©T©wIP"
#define SYSLOG_USB_DISCONNECT_THERING_DEVICE  "USBºô¸ô¦@¨É³]³Æ¤wÂ÷½u"
#define SYSLOG_USB_FIND_THERING_DEVICE  "USBºô¸ô¦@¨É³]³Æ¤w³s±µ"
#define SYSLOG_USB_STORAGE_DETECTED "¤w°»´ú¨ìUSBÀx¦sªÅ¶¡(USB%d)"
#define SYSLOG_USB_STORAGE_MOUNT "USBÀx¦sªÅ¶¡¤w±Ò¥Î(USB%d)"
#define SYSLOG_USB_STORAGE_REMOVED "USBÀx¦sªÅ¶¡¤w©Þ°£(USB%d)"
#define SYSLOG_USB_STORAGE_UNMOUNT "USBÀx¦sªÅ¶¡¤w°±¥Î(USB%d)"
#define SYSLOG_WIFI_EXT_APPLY_MACAUTH  "µL½uMACÅçÃÒ³]©w¤w§ó·s¦Û³s½uAP"
#define SYSLOG_WIFI_EXT_APPLY_WIFISCHED  "µL½u±Æµ{³]©w¤w§ó·s¦Û³s½uAP"
#define SYSLOG_WIFI_SCHED_START_WIFI "[µL½u±Æµ{] %s µL½uºô¸ô¤w«ì´_"
#define SYSLOG_WIFI_SCHED_STOP_WIFI "[µL½u±Æµ{] %s µL½uºô¸ô¤w°±¤î"
