top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/aaa
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/aaa
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/aaa

include $(top_srcdir)/build/special.mk

