top_srcdir   = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
top_builddir = /home/bcmac/userapps/nasapp/source/httpd-2.4.3
srcdir       = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/generators
builddir     = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/generators
VPATH        = /home/bcmac/userapps/nasapp/source/httpd-2.4.3/modules/generators

include $(top_srcdir)/build/special.mk

